apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-initdb-config
data:
  init-mongo.js: |
    db.getSiblingDB('n8n-chat-memory').createCollection('chat_sessions');
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mongodb
  labels:
    app: mongodb
spec:
  #type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  serviceName: svc-mongodb 
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-csi-data
          mountPath: /data/db
        - name: init-mongo-volume
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
      - name: mongodb-csi-data
        persistentVolumeClaim:
          claimName: pvc-nfs-mongodb
      - name: init-mongo-volume
        configMap:
          name: mongodb-initdb-config
