apiVersion: v1
kind: Service
metadata:
  labels:
    app: n8n
  name: svc-n8n
  namespace: default
spec:
  #type: LoadBalancer
  ports:
  - port: 5678
  selector:
    app: n8n
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: n8n
  name: n8n
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: install-deps
        image: n8nio/n8n:latest 
        volumeMounts:
        - name: n8n-csi-data
          mountPath: /home/node/.n8n
        command: ['/bin/sh', '-c']
        args:
          - cd /home/node/.n8n && npm install uuid; 
      containers:
      - image: n8nio/n8n:latest
        name: n8n 
        command: ["n8n"]
        args: ["start", "--tunnel"]
        ports:
        - containerPort: 5678
        env:
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        - name: N8N_EDITOR_BASE_URL
          value: "http://localhost:5678"
        - name: N8N_PROTOCOL
          value: "http"
        - name: N8N_PORT
          value: "5678"
        - name: GENERIC_TIMEZONE
          value: "Asia/Tokyo"
        - name: N8N_SECURE_COOKIE
          value: "false"
        - name: NODE_FUNCTION_ALLOW_EXTERNAL
          value: "uuid"
        - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
          value: "true"
        - name: N8N_EXPRESS_TRUST_PROXY
          value: "true"
        - name: DB_SQLITE_POOL_SIZE
          value: "5"
        - name: N8N_RUNNERS_ENABLED
          value: "true"
        - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
          value: "false"
        - name: N8N_GIT_NODE_DISABLE_BARE_REPOS
          value: "true"
        - name: N8N_PROXY_HOPS
          value: "1"
        volumeMounts:
        - name: n8n-csi-data
          mountPath: /home/node/.n8n
      volumes:
      - name: n8n-csi-data
        #emptyDir: {}
        persistentVolumeClaim:
          claimName: pvc-nfs-n8n
